server:
  port: 8085
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: reactivehub     # ws://localhost:8080/climateData
          uri: lb://reactivehub    
          predicates:
            - Path=/climateData/**
        - id: reactivehub     
          uri: lb:ws://reactivehub    
          predicates:
            - Path=/climateData/**
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://servicio-eureka-server:8761/eureka/


